import { useEffect, useState } from 'react'
import {
  ArrowDownRight,
  Check,
  ChevronRight,
  Clipboard,
  Heart,
  LockKeyhole,
  MessageCircle,
  RefreshCw,
  Send,
  ShieldCheck,
  Sparkles,
} from 'lucide-react'
import { checkHealth, generateReplies } from './lib/api.js'

const tones = [
  { name: 'Friendly', emoji: '😊', hint: 'Warm & open' },
  { name: 'Casual', emoji: '😎', hint: 'Easygoing' },
  { name: 'Professional', emoji: '💼', hint: 'Clear & polished' },
  { name: 'Funny', emoji: '😂', hint: 'A little playful' },
  { name: 'Caring', emoji: '❤️', hint: 'Thoughtful' },
  { name: 'Polite', emoji: '🙏', hint: 'Considerate' },
]

const sampleMessage = 'Hey, can you send me the project files by tonight?'

export default function App() {
  const [message, setMessage] = useState('')
  const [tone, setTone] = useState('Friendly')
  const [styleExamples, setStyleExamples] = useState('')
  const [context, setContext] = useState('')
  const [replies, setReplies] = useState([])
  const [model, setModel] = useState('gemma3:1b')
  const [runtime, setRuntime] = useState('checking')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [copied, setCopied] = useState(-1)

  useEffect(() => {
    checkHealth()
      .then((health) => {
        setModel(health.model)
        setRuntime(health.ollama_available ? (health.model_ready ? 'ready' : 'model-missing') : 'offline')
      })
      .catch(() => setRuntime('offline'))
  }, [])

  async function handleGenerate(event) {
    event?.preventDefault()
    if (!message.trim()) {
      setError('Add the message you received first.')
      return
    }
    setLoading(true)
    setError('')
    setReplies([])
    try {
      const result = await generateReplies({
        message: message.trim(),
        tone,
        style_examples: styleExamples.trim(),
        context: context.trim(),
      })
      setReplies(result.replies)
      setModel(result.model)
      setRuntime('ready')
    } catch (requestError) {
      setError(requestError.message)
    } finally {
      setLoading(false)
    }
  }

  async function handleCopy(reply, index) {
    try {
      await navigator.clipboard.writeText(reply)
      setCopied(index)
      window.setTimeout(() => setCopied(-1), 1800)
    } catch {
      setError('Clipboard access is unavailable. Select the reply and copy it instead.')
    }
  }

  function loadExample() {
    setMessage(sampleMessage)
    setTone('Friendly')
    setError('')
  }

  const runtimeLabel = {
    checking: 'Checking local AI',
    ready: `${model} · ready`,
    'model-missing': `${model} · model needed`,
    offline: 'Local AI not connected',
  }[runtime]

  return (
    <div className="app-shell">
      <header className="topbar">
        <a className="brand" href="#top" aria-label="ReplyBuddy home">
          <span className="brand-mark"><MessageCircle size={21} strokeWidth={2.3} /></span>
          <span>replybuddy<span className="brand-period">.</span></span>
        </a>
        <div className="topbar-right">
          <div className={`model-pill ${runtime}`} title="Replies are generated by a model running on your own computer">
            <span className="status-dot" />
            <span>{runtimeLabel}</span>
          </div>
          <a className="github-link" href="https://dev.to/challenges/hacktoberfest-weekend-2026-10-01" target="_blank" rel="noreferrer">
            Made for a friend <Heart size={14} fill="currentColor" />
          </a>
        </div>
      </header>

      <main id="top">
        <section className="hero">
          <div className="hero-copy">
            <div className="eyebrow"><span className="eyebrow-line" /> YOUR WORDS, JUST A LITTLE HELP</div>
            <h1>The right words,<br /><span>still yours.</span></h1>
            <p className="hero-description">For the moments when you know what you mean, but aren’t quite sure how to say it. Pick a tone, add your own style, and make it sound like <em>you</em>.</p>
            <div className="hero-trust"><span><LockKeyhole size={14} /> Private by design</span><i /> <span>Runs on your device</span></div>
          </div>
          <div className="hero-note" aria-label="A note for a friend">
            <div className="note-sparkle"><Sparkles size={16} /></div>
            <p>“Sometimes you just need<br />a little help finding<br />the words.”</p>
            <span>— made for someone I care about</span>
            <ArrowDownRight className="note-arrow" size={25} />
          </div>
        </section>

        <div className="workspace">
          <form className="composer panel" onSubmit={handleGenerate}>
            <div className="section-heading">
              <div className="step-number">01</div>
              <div><h2>What did they say?</h2><p>Paste the message you’re replying to.</p></div>
            </div>
            <div className="message-field-wrap">
              <textarea
                className="message-field"
                value={message}
                onChange={(event) => setMessage(event.target.value)}
                placeholder="Paste or type a message here…"
                maxLength={2000}
                aria-label="Message you received"
                required
              />
              <div className="field-footer">
                <button className="text-button" type="button" onClick={loadExample}><Sparkles size={14} /> Try an example</button>
                <span>{message.length}/2000</span>
              </div>
            </div>

            <div className="form-section tone-section">
              <div className="section-heading compact-heading">
                <div className="step-number">02</div>
                <div><h2>How should it feel?</h2><p>Choose the tone that fits.</p></div>
              </div>
              <div className="tone-grid" role="group" aria-label="Choose a reply tone">
                {tones.map((option) => (
                  <button
                    className={`tone-option ${tone === option.name ? 'selected' : ''}`}
                    key={option.name}
                    type="button"
                    aria-pressed={tone === option.name}
                    onClick={() => setTone(option.name)}
                  >
                    <span className="tone-emoji">{option.emoji}</span>
                    <span className="tone-copy"><strong>{option.name}</strong><small>{option.hint}</small></span>
                    {tone === option.name && <Check className="tone-check" size={15} />}
                  </button>
                ))}
              </div>
            </div>

            <details className="personalize">
              <summary><span className="personalize-icon"><Heart size={15} /></span><span><strong>Make it sound like me</strong><small>Optional · add a few examples of how you text</small></span><ChevronRight size={17} className="details-chevron" /></summary>
              <div className="personalize-fields">
                <label htmlFor="style-examples">A few messages you’ve written</label>
                <textarea id="style-examples" value={styleExamples} onChange={(event) => setStyleExamples(event.target.value)} maxLength={1000} placeholder={'“yeah no worries 😂”\n“suree, I’ll send it over”'} />
                <label htmlFor="context">A little context <span>(optional)</span></label>
                <input id="context" value={context} onChange={(event) => setContext(event.target.value)} maxLength={500} placeholder="e.g. This is a close friend asking for a favor" />
                <p className="privacy-hint"><ShieldCheck size={13} /> Style examples are only used for this reply. Nothing is saved.</p>
              </div>
            </details>

            {error && <div className="error-message" role="alert">{error}</div>}
            <button className="generate-button" type="submit" disabled={loading}>
              {loading ? <><span className="spinner" /> Finding your words…</> : <><Sparkles size={17} /> Generate 3 replies <Send size={15} className="button-arrow" /></>}
            </button>
            <p className="generate-footnote"><LockKeyhole size={12} /> Your messages stay on this device.</p>
          </form>

          <section className="results-column" aria-live="polite">
            <div className="results-header">
              <div>
                <div className="results-kicker">A LITTLE HELP, YOUR WAY</div>
                <h2>{replies.length ? 'Pick the one that feels right.' : 'Your replies will appear here.'}</h2>
              </div>
              {replies.length > 0 && <button className="regenerate-button" onClick={handleGenerate} disabled={loading}><RefreshCw size={14} /> Try again</button>}
            </div>

            {replies.length > 0 ? (
              <div className="reply-list">
                {replies.map((reply, index) => (
                  <article className="reply-card" key={`${index}-${reply}`}>
                    <div className="reply-card-top"><span className="reply-index">0{index + 1}</span><span className="reply-tone">{tones.find((item) => item.name === tone)?.emoji} {tone}</span></div>
                    <p>{reply}</p>
                    <button className={`copy-button ${copied === index ? 'copied' : ''}`} onClick={() => handleCopy(reply, index)}>
                      {copied === index ? <Check size={14} /> : <Clipboard size={14} />}
                      {copied === index ? 'Copied' : 'Copy reply'}
                    </button>
                  </article>
                ))}
                <div className="results-note"><Heart size={13} /> Tweak any reply so it feels like you.</div>
              </div>
            ) : (
              <div className="empty-state">
                <div className="empty-illustration">
                  <div className="bubble bubble-back">hey, are you free<br />this weekend?</div>
                  <div className="bubble bubble-front"><Sparkles size={16} /><span>Your reply<br />is on its way.</span></div>
                  <span className="illustration-star star-one">✳</span><span className="illustration-star star-two">✦</span>
                </div>
                <div className="empty-copy"><h3>Good conversations<br />start with feeling heard.</h3><p>Three thoughtful options. Your tone.<br />No blank-page panic.</p></div>
                <div className="empty-divider"><span /> A QUICK EXAMPLE <span /></div>
                <button className="example-card" type="button" onClick={loadExample}>
                  <span className="example-label">THE MESSAGE</span>
                  <span className="example-quote">“Can you send me the project files by tonight?”</span>
                  <span className="example-action">Try this one <ChevronRight size={14} /></span>
                </button>
              </div>
            )}
            <div className="local-note"><span className="local-note-icon"><ShieldCheck size={16} /></span><span><strong>Your conversations stay yours.</strong><br />With the default setup, replies run locally on an open-weight AI model and messages stay on this device.</span></div>
          </section>
        </div>

        <section className="how-it-works">
          <span className="how-label">SMALL TOOL, REAL CARE</span>
          <p>Built for the friend who always knows what they want to say <em>after</em> they hit send.</p>
          <span className="how-caption">A note to make everyday conversations feel a little easier.</span>
        </section>
      </main>

      <footer className="footer"><a className="footer-brand" href="#top">replybuddy<span>.</span></a><span>Made with care, and a little open AI.</span><a href="https://dev.to/challenges/hacktoberfest-weekend-2026-10-01" target="_blank" rel="noreferrer">Hacktoberfest · Build for a Friend</a></footer>
    </div>
  )
}
